plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
title: No stress front end
author: 
  name: Francesco Bedussi
  email: "francesco@francescobedussi.it"
description: A log of my journey to a better, simplier front end development
url: https://fbedussi.github.io/blog/
disqus:
  shortname: front-end-no-stress
minima:
  skin: solarized-light
  social_links:
    - { platform: github,  user_url: "https://github.com/fbedussi" }
    - { platform: mastodon, user_url: "https://mastodon.uno/@saiot", title: "mastodon" }
show_excerpts: true
header_pages:
  - about.md
