plugins:
  - jekyll-remote-theme
  - jekyll-feed
remote_theme: jekyll/minima
minima:
  skin: bedux
  
title: No stress front end
description: A journey to a healthier front end development
url: https://fbedussi.github.io/blog/

author: 
  name: Francesco Bedussi
  email: "francesco [at] francescobedussi.it"

disqus:
  shortname: front-end-no-stress

show_excerpts: true

header_pages:
  - search.html
  - about.md

permalink: /:categories/:title

tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
